version: 0.2
phases:
  pre_build:
    commands:
      # 1. Output a log message indicating the start of the ECR login process.
      - echo Logging in to Amazon ECR...
      
      # 2. Extract the AWS Account ID from the CodeBuild ARN environment variable.
      - AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -f 5 -d ':')
      
      # 3. Set the AWS region environment variable (e.g., eu-central-1).
      - AWS_DEFAULT_REGION=$AWS_REGION
      
      # 4. Construct the full URI for the ECR repository we created (todo-api-repo).
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/todo-api-repo
      
      # 5. Log in to ECR securely using the Docker client and AWS credentials.
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Build started on `date`
      
      # 6. Extract the first 7 characters of the Git commit ID to use as a unique image tag.
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      
      # 7. Build the Docker image using the Dockerfile in the root directory and tag it as 'latest'.
      - docker build -t $REPOSITORY_URI:latest .
      
      # 8. Tag the image with the unique commit ID (e.g., todo-api-repo:abcdef1).
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      
      # 9. Push the 'latest' tagged image to the ECR repository.
      - docker push $REPOSITORY_URI:latest
      
      # 10. Push the unique commit-tagged image to ECR.
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      
      # 11. Create a JSON file with the image details (required by CodePipeline for deployment tools).
      - printf '[{"name":"todo-api-repo","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    # 12. Specify the output JSON file as an artifact of the build stage.
    - imagedefinitions.json
